Repository ACLPManager/manager, pull requests merged in 2024-10, with the labels that each got.

#11 upcoming: [DI-21254] - Handle unit using reference values
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
Labels: Additional Approval Required

#12 Feature/aclp cypress automation final
  packages/manager/.changeset/pr-10891-tests-1726565438335.md
  packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-navigation.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
  packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
  packages/manager/cypress/support/constants/widgets.ts
  packages/manager/cypress/support/intercepts/cloudpulse.ts
  packages/manager/cypress/support/ui/autocomplete.ts
  packages/manager/cypress/support/util/cloudpulse.ts
  packages/manager/src/components/Autocomplete/Autocomplete.tsx
  packages/manager/src/components/LineGraph/LineGraph.tsx
  packages/manager/src/factories/dashboards.ts
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.test.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/Widget/components/CloudPulseAggregateFunction.tsx
  packages/manager/src/features/CloudPulse/Widget/components/Zoomer.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseCustomSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTimeRangeSelect.tsx
Labels: Ready for Review

#20 DI-20837 - Handle new label property for services while selecting dashboard
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/src/factories/index.ts
  packages/manager/src/factories/services.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
  packages/manager/src/mocks/serverHandlers.ts
Labels: Approved, Ready for Review
