Repository ACLPManager/manager, pull requests merged in 2025-01, with the labels that each got.

#132 upcoming: [DI-22714] - Metrics call request update
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/src/factories/dashboards.ts
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.test.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidgetRenderer.tsx
Labels: First PR 2025

#121 upcoming: [DI-22558] - Notification channel changes
  packages/api-v4/src/cloudpulse/alerts.ts
  packages/manager/src/factories/index.ts
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetailNotification.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetailNotification.tsx
  packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
  packages/manager/src/features/CloudPulse/Alerts/Utils/utils.ts
  packages/manager/src/mocks/serverHandlers.ts
  packages/manager/src/queries/cloudpulse/alerts.ts
  packages/manager/src/queries/cloudpulse/queries.ts
  packages/manager/src/queries/cloudpulse/requests.ts
Labels: Ready for Review, CloudPulse-Alerting

#141 Date range picker
  packages/api-v4/src/cloudpulse/types.ts
  packages/manager/src/components/DatePicker/DateTimePicker.tsx
  packages/manager/src/components/DatePicker/DateTimeRangePicker.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboard.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx
  packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.test.tsx
  packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
  packages/manager/src/features/CloudPulse/Utils/CloudPulseDateTimePickerUtils.ts
  packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.test.ts
  packages/manager/src/features/CloudPulse/Utils/ReusableDashboardFilterUtils.ts
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.test.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
  packages/manager/src/features/CloudPulse/Widget/CloudPulseWidgetRenderer.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDateTimeRangePicker.tsx
  packages/manager/src/features/Databases/DatabaseDetail/DatabaseMonitor/DatabaseMonitor.test.tsx
Labels: question, Ready for Review

#149 Fixed bugs identified by anantha
  packages/manager/src/components/DatePicker/DateTimeRangePicker.test.tsx
  packages/manager/src/components/DatePicker/DateTimeRangePicker.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseDateTimeRangePicker.tsx
Labels: Don't Merge

#144 Feature/alerts listing pagination filtering ordering
  packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.test.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertsListTable.tsx
  packages/manager/src/features/CloudPulse/Alerts/AlertsListing/constants.ts
  packages/manager/src/features/CloudPulse/Alerts/constants.ts
  packages/manager/src/mocks/serverHandlers.ts
Labels: CloudPulse-Alerting

#154 upcoming: [DI-20931] - Updated test cases
  packages/manager/src/components/DatePicker/DateTimeRangePicker.test.tsx
  packages/manager/src/components/DatePicker/DateTimeRangePicker.tsx
Labels: Don't Merge

#170 upcoming: [DI-22941] - Update dependency and order for tags
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
  packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
  packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
  packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTagsFilter.test.tsx
  packages/manager/src/features/CloudPulse/shared/CloudPulseTagsFilter.tsx
Labels: cypress update required
